name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn types:build
          start: yarn dev:ci
          command: yarn test:cy-run
        env:
          NEXT_PUBLIC_FAUNA_GRAPHQL_URI: ${{ secrets.FAUNA_GRAPHQL_URI }}
          FAUNA_ADMIN_KEY: ${{ secrets.FAUNA_ADMIN_KEY }}
